version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Password"  # Set your SQL Server sa password here
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # SQL Server port
    networks:
      - mynetwork

  yourapp:
    build: .
    ports:
      - "5000:80"  # Expose your .NET application port
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      CONNECTIONSTRINGS__DEFAULTCONNECTION: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      RABBITMQ__HOSTNAME: ${RABBITMQ__HOSTNAME}
    networks:
      - mynetwork

networks:
  mynetwork: